In [1]:
import pandas as pd

In [120]:
df1 = pd.read_csv(r"D:\Ankitha\2nd Yr\Term - 1\Big Data Analytics\Project\final_crime_dataset_1.csv")
df1["source_dataset"] = "crime_dataset_1"

df2 = pd.read_csv(r"D:\Ankitha\2nd Yr\Term - 1\Big Data Analytics\Project\final_ncrb_women_crimes.csv")
df2["source_dataset"] = "ncrb_women"

df3 = pd.read_csv(r"D:\Ankitha\2nd Yr\Term - 1\Big Data Analytics\Project\final_women_children_crimedata_cleaned.csv")
df3["source_dataset"] = "women_children"

df4 = pd.read_csv(r"D:\Ankitha\2nd Yr\Term - 1\Big Data Analytics\Project\final_outdoor_women_crimes_2017_normalized.csv")
df4["source_dataset"] = "outdoor_2017"

df5 = pd.read_csv(r"D:\Ankitha\2nd Yr\Term - 1\Big Data Analytics\Project\final_women_outdoor_crimes_2024.csv")
df5["source_dataset"] = "outdoor_2024"

In [121]:
print(df5.head())
print(df5.columns.tolist())

        CCN                 REPORT_DAT                 START_DATE  \
0  24001558  2024-01-04 02:09:24+00:00  2024-01-03 23:03:00+00:00
1  24019819  2024-02-08 04:29:10+00:00  2024-02-08 01:25:00+00:00
2  24022148  2024-02-12 16:25:56+00:00  2024-02-12 15:30:00+00:00
3  24005258  2024-01-11 13:51:09+00:00  2024-01-11 12:10:00+00:00
4  24005185  2024-01-11 07:35:50+00:00  2024-01-11 04:56:00+00:00

                    END_DATE     SHIFT                     OFFENSE  \
0  2024-01-04 00:26:00+00:00   EVENING  ASSAULT W/DANGEROUS WEAPON
1  2024-02-09 03:30:00+00:00  MIDNIGHT  ASSAULT W/DANGEROUS WEAPON
2  2024-02-12 16:15:00+00:00       DAY  ASSAULT W/DANGEROUS WEAPON
3  2024-01-11 12:15:00+00:00       DAY  ASSAULT W/DANGEROUS WEAPON
4  2024-01-11 04:59:00+00:00  MIDNIGHT  ASSAULT W/DANGEROUS WEAPON

                                               BLOCK  WARD  DISTRICT  \
0                 1953 - 2099 BLOCK OF 19TH PLACE SE   8.0       7.0
1  3900 - 3999 BLOCK OF MARTIN LUTHER KING JR AVE...   8.0       7.0
2              1737 - 1776 BLOCK OF COLUMBIA ROAD NW   1.0       3.0
3              100 - 199 BLOCK OF ATLANTIC STREET SE   8.0       7.0
4             1000 - 1099 BLOCK OF WEBSTER STREET NW   4.0       4.0

  NEIGHBORHOOD_CLUSTER  ...  time_period  crime_count  \
0           Cluster 28  ...        Night            1
1           Cluster 39  ...        Night            1
2            Cluster 1  ...    Afternoon            1
3           Cluster 39  ...    Afternoon            1
4           Cluster 18  ...        Night            1

                   crime_type                 crime_date  crime_hour  year  \
0  ASSAULT W/DANGEROUS WEAPON  2024-01-04 02:09:24+00:00           2  2024
1  ASSAULT W/DANGEROUS WEAPON  2024-02-08 04:29:10+00:00           4  2024
2  ASSAULT W/DANGEROUS WEAPON  2024-02-12 16:25:56+00:00          16  2024
3  ASSAULT W/DANGEROUS WEAPON  2024-01-11 13:51:09+00:00          13  2024
4  ASSAULT W/DANGEROUS WEAPON  2024-01-11 07:35:50+00:00           7  2024

  day_night        area risk_level source_dataset
0     Night  Cluster 28     Medium   outdoor_2024
1     Night  Cluster 39       High   outdoor_2024
2       Day   Cluster 1     Medium   outdoor_2024
3       Day  Cluster 39       High   outdoor_2024
4       Day  Cluster 18       High   outdoor_2024

[5 rows x 26 columns]
['CCN', 'REPORT_DAT', 'START_DATE', 'END_DATE', 'SHIFT', 'OFFENSE', 'BLOCK', 'WARD', 'DISTRICT', 'NEIGHBORHOOD_CLUSTER', 'LATITUDE', 'LONGITUDE', 'hour', 'day', 'month', 'weekday', 'time_period', 'crime_count', 'crime_type', 'crime_date', 'crime_hour', 'year', 'day_night', 'area', 'risk_level', 'source_dataset']

In [14]:
def standardize(df):
    df.columns = df.columns.str.lower().str.strip()
    return df

In [15]:
df1 = standardize(df1)
df2 = standardize(df2)
df3 = standardize(df3)
df4 = standardize(df4)
df5 = standardize(df5)

In [16]:
df1["area_type"] = "CITY"

In [17]:
df1

,area,crime_type,year,crime_count,crime_date,crime_hour,day_night,month,risk_level,source_dataset,area_type
0,Ludhiana,KIDNAPPING,2020,1,01-01-2020 02:00,2,Night,1,Medium,crime_dataset_1,CITY
1,Bangalore,SEXUAL ASSAULT,2020,1,01-01-2020 14:00,14,Day,1,High,crime_dataset_1,CITY
2,Lucknow,SEXUAL ASSAULT,2020,1,02-01-2020 12:00,12,Day,1,High,crime_dataset_1,CITY
3,Kanpur,SEXUAL ASSAULT,2020,1,03-01-2020 08:00,8,Day,1,Medium,crime_dataset_1,CITY
4,Ahmedabad,ASSAULT,2020,1,03-01-2020 09:00,9,Day,1,High,crime_dataset_1,CITY
...,...,...,...,...,...,...,...,...,...,...,...
3196,Bangalore,SEXUAL ASSAULT,2024,1,29-07-2024 14:00,14,Day,7,High,crime_dataset_1,CITY
3197,Mumbai,KIDNAPPING,2024,1,29-07-2024 19:00,19,Night,7,High,crime_dataset_1,CITY
3198,Chennai,KIDNAPPING,2024,1,29-07-2024 21:00,21,Night,7,High,crime_dataset_1,CITY
3199,Indore,ASSAULT,2024,1,30-07-2024 12:00,12,Day,7,Medium,crime_dataset_1,CITY
3200,Mumbai,KIDNAPPING,2024,1,30-07-2024 23:00,23,Night,7,High,crime_dataset_1,CITY

In [118]:
df2["area_type"] = "DISTRICT"

df4["area_type"] = "DISTRICT"

In [19]:
df2

,state,district,year,crime_type,crime_count,source_dataset,area_type
0,ANDHRA PRADESH,ADILABAD,2001,RAPE,50,ncrb_women,DISTRICT
1,ANDHRA PRADESH,ANANTAPUR,2001,RAPE,23,ncrb_women,DISTRICT
2,ANDHRA PRADESH,CHITTOOR,2001,RAPE,27,ncrb_women,DISTRICT
3,ANDHRA PRADESH,CUDDAPAH,2001,RAPE,20,ncrb_women,DISTRICT
4,ANDHRA PRADESH,EAST GODAVARI,2001,RAPE,23,ncrb_women,DISTRICT
...,...,...,...,...,...,...,...
40795,JAMMU & KASHMIR,SOPORE,2020,ASSAULT,101,ncrb_women,DISTRICT
40796,JAMMU & KASHMIR,SRINAGAR,2020,ASSAULT,186,ncrb_women,DISTRICT
40797,JAMMU & KASHMIR,UDHAMPUR,2020,ASSAULT,30,ncrb_women,DISTRICT
40798,LAKSHADWEEP,LAKSHADWEEP,2020,ASSAULT,3,ncrb_women,DISTRICT
40799,PUDUCHERRY,PUDUCHERRY,2020,ASSAULT,25,ncrb_women,DISTRICT

In [21]:
df4

,year,state,district,crime_type,crime_count,source_dataset,area_type
0,2017,ANDHRA PRADESH,ANANTHAPURAMU,RAPE_WOMEN_ABOVE_18,20,outdoor_2017,DISTRICT
1,2017,ANDHRA PRADESH,CHITTOOR,RAPE_WOMEN_ABOVE_18,6,outdoor_2017,DISTRICT
2,2017,ANDHRA PRADESH,Y.S.R.,RAPE_WOMEN_ABOVE_18,23,outdoor_2017,DISTRICT
3,2017,ANDHRA PRADESH,EAST GODAVARI,RAPE_WOMEN_ABOVE_18,19,outdoor_2017,DISTRICT
4,2017,ANDHRA PRADESH,GUNTUR,RAPE_WOMEN_ABOVE_18,32,outdoor_2017,DISTRICT
...,...,...,...,...,...,...,...
26246,2022,ASSAM,TAMULPUR,PROCURATION_OF_MINOR_GIRLS,21,outdoor_2017,DISTRICT
26247,2022,MADHYA PRADESH,BHOPAL,PROCURATION_OF_MINOR_GIRLS,2,outdoor_2017,DISTRICT
26248,2022,MADHYA PRADESH,INDORE,PROCURATION_OF_MINOR_GIRLS,1,outdoor_2017,DISTRICT
26249,2022,SIKKIM,NAMCHI,PROCURATION_OF_MINOR_GIRLS,1,outdoor_2017,DISTRICT
26250,2022,TAMIL NADU,THIRUVALLUR,PROCURATION_OF_MINOR_GIRLS,2,outdoor_2017,DISTRICT

In [22]:
df5["area_type"] = "CLUSTER"

In [23]:
df5

,ccn,report_dat,start_date,end_date,shift,offense,block,ward,district,neighborhood_cluster,...,crime_count,crime_type,crime_date,crime_hour,year,day_night,area,risk_level,source_dataset,area_type
0,24001558,2024-01-04 02:09:24+00:00,2024-01-03 23:03:00+00:00,2024-01-04 00:26:00+00:00,EVENING,ASSAULT W/DANGEROUS WEAPON,1953 - 2099 BLOCK OF 19TH PLACE SE,8.0,7.0,Cluster 28,...,1,ASSAULT W/DANGEROUS WEAPON,2024-01-04 02:09:24+00:00,2,2024,Night,Cluster 28,Medium,outdoor_2024,CLUSTER
1,24019819,2024-02-08 04:29:10+00:00,2024-02-08 01:25:00+00:00,2024-02-09 03:30:00+00:00,MIDNIGHT,ASSAULT W/DANGEROUS WEAPON,3900 - 3999 BLOCK OF MARTIN LUTHER KING JR AVE...,8.0,7.0,Cluster 39,...,1,ASSAULT W/DANGEROUS WEAPON,2024-02-08 04:29:10+00:00,4,2024,Night,Cluster 39,High,outdoor_2024,CLUSTER
2,24022148,2024-02-12 16:25:56+00:00,2024-02-12 15:30:00+00:00,2024-02-12 16:15:00+00:00,DAY,ASSAULT W/DANGEROUS WEAPON,1737 - 1776 BLOCK OF COLUMBIA ROAD NW,1.0,3.0,Cluster 1,...,1,ASSAULT W/DANGEROUS WEAPON,2024-02-12 16:25:56+00:00,16,2024,Day,Cluster 1,Medium,outdoor_2024,CLUSTER
3,24005258,2024-01-11 13:51:09+00:00,2024-01-11 12:10:00+00:00,2024-01-11 12:15:00+00:00,DAY,ASSAULT W/DANGEROUS WEAPON,100 - 199 BLOCK OF ATLANTIC STREET SE,8.0,7.0,Cluster 39,...,1,ASSAULT W/DANGEROUS WEAPON,2024-01-11 13:51:09+00:00,13,2024,Day,Cluster 39,High,outdoor_2024,CLUSTER
4,24005185,2024-01-11 07:35:50+00:00,2024-01-11 04:56:00+00:00,2024-01-11 04:59:00+00:00,MIDNIGHT,ASSAULT W/DANGEROUS WEAPON,1000 - 1099 BLOCK OF WEBSTER STREET NW,4.0,4.0,Cluster 18,...,1,ASSAULT W/DANGEROUS WEAPON,2024-01-11 07:35:50+00:00,7,2024,Day,Cluster 18,High,outdoor_2024,CLUSTER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1023,24179007,2024-11-18 04:45:09+00:00,2024-11-18 02:38:00+00:00,2024-11-18 03:15:00+00:00,MIDNIGHT,ASSAULT W/DANGEROUS WEAPON,3200 - 3299 BLOCK OF MOUNT PLEASANT STREET NW,1.0,3.0,Cluster 2,...,1,ASSAULT W/DANGEROUS WEAPON,2024-11-18 04:45:09+00:00,4,2024,Night,Cluster 2,High,outdoor_2024,CLUSTER
1024,24016967,2024-02-03 01:03:11+00:00,2024-02-02 23:37:00+00:00,2024-02-03 01:03:00+00:00,EVENING,ASSAULT W/DANGEROUS WEAPON,1400 - 1499 BLOCK OF RHODE ISLAND AVENUE NW,2.0,2.0,Cluster 7,...,1,ASSAULT W/DANGEROUS WEAPON,2024-02-03 01:03:11+00:00,1,2024,Night,Cluster 7,Medium,outdoor_2024,CLUSTER
1025,24018397,2024-02-06 01:11:29+00:00,2024-02-05 20:39:00+00:00,2024-02-05 23:00:00+00:00,EVENING,ASSAULT W/DANGEROUS WEAPON,3900 - 3920 BLOCK OF 1ST STREET SE,8.0,7.0,Cluster 39,...,1,ASSAULT W/DANGEROUS WEAPON,2024-02-06 01:11:29+00:00,1,2024,Night,Cluster 39,High,outdoor_2024,CLUSTER
1026,24088908,2024-06-11 23:39:23+00:00,2024-06-11 20:22:00+00:00,2024-06-11 23:30:00+00:00,EVENING,ASSAULT W/DANGEROUS WEAPON,4000 - 4099 BLOCK OF KANSAS AVENUE NW,4.0,4.0,Cluster 18,...,1,ASSAULT W/DANGEROUS WEAPON,2024-06-11 23:39:23+00:00,23,2024,Night,Cluster 18,High,outdoor_2024,CLUSTER
1027,24168445,2024-10-30 09:14:00+00:00,2024-10-30 08:39:00+00:00,2024-10-30 10:00:00+00:00,MIDNIGHT,ASSAULT W/DANGEROUS WEAPON,81 - 199 BLOCK OF 55TH STREET SE,7.0,6.0,Cluster 33,...,1,ASSAULT W/DANGEROUS WEAPON,2024-10-30 09:14:00+00:00,9,2024,Day,Cluster 33,High,outdoor_2024,CLUSTER

In [27]:
df2["area"] = (
    df2["state"].str.upper().str.strip() + " - " +
    df2["district"].str.upper().str.strip()
)

df2["area_type"] = "DISTRICT"

In [29]:
df4["area"] = (
    df4["state"].str.upper().str.strip() + " - " +
    df4["district"].str.upper().str.strip()
)

df4["area_type"] = "DISTRICT"

In [30]:
df5["area"] = df5["neighborhood_cluster"].astype(str).str.upper()
df5["area_type"] = "CLUSTER"

In [35]:
df2[["state", "district", "area"]].head()

            state       district                            area
0  ANDHRA PRADESH       ADILABAD       ANDHRA PRADESH - ADILABAD
1  ANDHRA PRADESH      ANANTAPUR      ANDHRA PRADESH - ANANTAPUR
2  ANDHRA PRADESH       CHITTOOR       ANDHRA PRADESH - CHITTOOR
3  ANDHRA PRADESH       CUDDAPAH       ANDHRA PRADESH - CUDDAPAH
4  ANDHRA PRADESH  EAST GODAVARI  ANDHRA PRADESH - EAST GODAVARI

In [33]:
df4[["state", "district", "area"]].head()

            state       district                            area
0  ANDHRA PRADESH  ANANTHAPURAMU  ANDHRA PRADESH - ANANTHAPURAMU
1  ANDHRA PRADESH       CHITTOOR       ANDHRA PRADESH - CHITTOOR
2  ANDHRA PRADESH         Y.S.R.         ANDHRA PRADESH - Y.S.R.
3  ANDHRA PRADESH  EAST GODAVARI  ANDHRA PRADESH - EAST GODAVARI
4  ANDHRA PRADESH         GUNTUR         ANDHRA PRADESH - GUNTUR

In [34]:
df5[["neighborhood_cluster", "area"]].head()

  neighborhood_cluster        area
0           Cluster 28  CLUSTER 28
1           Cluster 39  CLUSTER 39
2            Cluster 1   CLUSTER 1
3           Cluster 39  CLUSTER 39
4           Cluster 18  CLUSTER 18

In [39]:
df2["area"].nunique()

1301

In [37]:
df4["area"].nunique()

768

In [38]:
df5["area"].nunique()

43

In [73]:
event_columns = [
    "area", "crime_type", "year", "crime_count",
    "crime_date", "crime_hour", "day_night",
    "risk_level", "latitude", "longitude",
    "source_dataset"
]

In [74]:
df1 = df1.reindex(columns=event_columns)
df5 = df5.reindex(columns=event_columns)

In [75]:
event_df = pd.concat([df1, df5], ignore_index=True)

In [76]:

event_df.shape

(4229, 11)

In [77]:
event_df.head()

,area,crime_type,year,crime_count,crime_date,crime_hour,day_night,risk_level,latitude,longitude,source_dataset
0,Ludhiana,KIDNAPPING,2020,1,NaN,NaN,NaN,NaN,NaN,NaN,crime_dataset_1
1,Bangalore,SEXUAL ASSAULT,2020,1,NaN,NaN,NaN,NaN,NaN,NaN,crime_dataset_1
2,Lucknow,SEXUAL ASSAULT,2020,1,NaN,NaN,NaN,NaN,NaN,NaN,crime_dataset_1
3,Kanpur,SEXUAL ASSAULT,2020,1,NaN,NaN,NaN,NaN,NaN,NaN,crime_dataset_1
4,Ahmedabad,ASSAULT,2020,1,NaN,NaN,NaN,NaN,NaN,NaN,crime_dataset_1

In [78]:

event_df.columns

Index(['area', 'crime_type', 'year', 'crime_count', 'crime_date', 'crime_hour',
       'day_night', 'risk_level', 'latitude', 'longitude', 'source_dataset'],
      dtype='object')

In [79]:
df1["source_dataset"] = "crime_dataset_1"
df5["source_dataset"] = "outdoor_2024"

In [81]:
import numpy as np   # ✅ REQUIRED

df1_event = df1[
    [
        "area",
        "crime_type",
        "year",
        "crime_count",
        "crime_date",
        "crime_hour",
        "day_night",
        "source_dataset"
    ]
].copy()

# df1 does not have coordinates → keep NaN (THIS IS CORRECT)
df1_event["latitude"] = np.nan
df1_event["longitude"] = np.nan

In [82]:
df1_event.head()

,area,crime_type,year,crime_count,crime_date,crime_hour,day_night,source_dataset,latitude,longitude
0,Ludhiana,KIDNAPPING,2020,1,NaN,NaN,NaN,crime_dataset_1,NaN,NaN
1,Bangalore,SEXUAL ASSAULT,2020,1,NaN,NaN,NaN,crime_dataset_1,NaN,NaN
2,Lucknow,SEXUAL ASSAULT,2020,1,NaN,NaN,NaN,crime_dataset_1,NaN,NaN
3,Kanpur,SEXUAL ASSAULT,2020,1,NaN,NaN,NaN,crime_dataset_1,NaN,NaN
4,Ahmedabad,ASSAULT,2020,1,NaN,NaN,NaN,crime_dataset_1,NaN,NaN

In [84]:

df5_event = df5[[
    "area",
    "crime_type",
    "year",
    "crime_count",
    "crime_date",
    "crime_hour",
    "day_night",
    "latitude",
    "longitude",
    "source_dataset"
]].copy()

In [85]:
event_df = pd.concat([df1_event, df5_event], ignore_index=True)

In [86]:
event_df.head()

,area,crime_type,year,crime_count,crime_date,crime_hour,day_night,source_dataset,latitude,longitude
0,Ludhiana,KIDNAPPING,2020,1,NaN,NaN,NaN,crime_dataset_1,NaN,NaN
1,Bangalore,SEXUAL ASSAULT,2020,1,NaN,NaN,NaN,crime_dataset_1,NaN,NaN
2,Lucknow,SEXUAL ASSAULT,2020,1,NaN,NaN,NaN,crime_dataset_1,NaN,NaN
3,Kanpur,SEXUAL ASSAULT,2020,1,NaN,NaN,NaN,crime_dataset_1,NaN,NaN
4,Ahmedabad,ASSAULT,2020,1,NaN,NaN,NaN,crime_dataset_1,NaN,NaN

In [87]:
event_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4229 entries, 0 to 4228
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   area            4229 non-null   object
 1   crime_type      4229 non-null   object
 2   year            4229 non-null   int64
 3   crime_count     4229 non-null   int64
 4   crime_date      0 non-null      float64
 5   crime_hour      0 non-null      float64
 6   day_night       0 non-null      float64
 7   source_dataset  4229 non-null   object
 8   latitude        0 non-null      float64
 9   longitude       0 non-null      float64
dtypes: float64(5), int64(2), object(3)
memory usage: 330.5+ KB

In [88]:
event_df.to_csv("final_event_level_dataset.csv", index=False)

In [92]:
df2 = pd.read_csv(r"D:\Ankitha\2nd Yr\Term - 1\Big Data Analytics\Project\final_ncrb_women_crimes.csv")
df4 = pd.read_csv(r"D:\Ankitha\2nd Yr\Term - 1\Big Data Analytics\Project\final_outdoor_women_crimes_2017_normalized.csv")

In [93]:
df2["source_dataset"] = "ncrb_women"
df4["source_dataset"] = "outdoor_2017"

In [97]:
df2 = df2[df2["District"].str.upper() != "TOTAL"]
df4 = df4[df4["district"].str.upper() != "TOTAL"]

In [95]:
print(df2.columns.tolist())
print(df4.columns.tolist())

['State', 'District', 'Year', 'Crime_Type', 'Crime_Count', 'source_dataset']
['year', 'state', 'district', 'crime_type', 'crime_count', 'source_dataset']

In [105]:
df2.columns = df2.columns.str.strip().str.lower()

In [106]:
df4.columns = df4.columns.str.strip().str.lower()

In [107]:
df2_agg = df2[[
    "state",
    "district",
    "year",
    "crime_type",
    "crime_count",
    "source_dataset"
]].copy()

df2_agg["area_type"] = "DISTRICT"

In [108]:
df4_agg = df4[[
    "state",
    "district",
    "year",
    "crime_type",
    "crime_count",
    "source_dataset"
]].copy()

df4_agg["area_type"] = "DISTRICT"

In [109]:
df2_agg = df2_agg[df2_agg["district"].str.upper() != "TOTAL"]
df4_agg = df4_agg[df4_agg["district"].str.upper() != "TOTAL"]

In [110]:
agg_df = pd.concat([df2_agg, df4_agg], ignore_index=True)

In [111]:
def calculate_risk(count):
    if count >= 500:
        return "High"
    elif count >= 100:
        return "Medium"
    else:
        return "Low"

In [112]:
agg_df["risk_level"] = agg_df["crime_count"].apply(calculate_risk)

In [113]:
agg_df[["district", "crime_count", "risk_level"]].head()

        district  crime_count risk_level
0       ADILABAD           50        Low
1      ANANTAPUR           23        Low
2       CHITTOOR           27        Low
3       CUDDAPAH           20        Low
4  EAST GODAVARI           23        Low

In [115]:
agg_df["risk_level"].value_counts()

risk_level
Low       57971
Medium     7119
High        277
Name: count, dtype: int64

In [116]:
agg_df.to_csv("final_aggregated_district_dataset.csv", index=False)

In [122]:
df3.to_csv("final_indicator_dataset.csv", index=False)

In [123]:
df3

,indicator,year,total_count,source_dataset
0,NUMBER OF WOMEN TRAFFICKED,2016,5239,women_children
1,NUMBER OF CHILDREN TRAFFICKED,2016,9034,women_children
2,NUMBER OF WOMEN VICTIMS OF TRAFFICKING RESCUED,2016,7238,women_children
3,NUMBER OF CHILD VICTIMS OF TRAFFICKING RESCUED,2016,14183,women_children
4,NUMBER OF WOMEN TRAFFICKED,2017,2040,women_children
5,NUMBER OF CHILDREN TRAFFICKED,2017,3535,women_children
6,NUMBER OF WOMEN VICTIMS OF TRAFFICKING RESCUED,2017,2211,women_children
7,NUMBER OF CHILD VICTIMS OF TRAFFICKING RESCUED,2017,3294,women_children
8,NUMBER OF WOMEN TRAFFICKED,2018,2472,women_children
9,NUMBER OF CHILDREN TRAFFICKED,2018,2834,women_children
10,NUMBER OF WOMEN VICTIMS OF TRAFFICKING RESCUED,2018,2493,women_children
11,NUMBER OF CHILD VICTIMS OF TRAFFICKING RESCUED,2018,2358,women_children

In [2]:
import pandas as pd

# Step 1: Load CSV with explicit delimiter
df = pd.read_csv(
    "final_crime_dataset_1.csv",
    sep=",",
    engine="python"
)

# Verify columns
print(df.columns)

Index(['area', 'crime_type', 'year', 'crime_count', 'crime_date', 'crime_hour',
       'day_night', 'month', 'risk_level'],
      dtype='object')

In [6]:
df["crime_date"] = pd.to_datetime(
    df["crime_date"],
    errors="coerce"
)

In [9]:
df["crime_date"] = pd.to_datetime(df["crime_date"], errors="coerce")
print("Invalid dates:", df["crime_date"].isna().sum())

Invalid dates: 1923

In [10]:
print("Invalid dates:", df["crime_date"].isna().sum())

Invalid dates: 1923

In [11]:
df_clean = df[df["crime_date"].notna()]

In [13]:
print("Invalid dates:", df_clean["crime_date"].isna().sum())

Invalid dates: 0

In [14]:
df_clean.to_csv("final_crime_dataset_1_cleaned.csv", index=False)
print("Final cleaned dataset saved successfully")

Final cleaned dataset saved successfully